
// actions register

export const REGISTER_ACCOUNT='REGISTER_ACCOUNT';
export const REGISTER_ACCOUNT_SUCCESS='REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL='REGISTER_ACCOUNT_FAIL';

// actions verify

export const VERIFY_ACCOUNT='VERIFY_ACCOUNT';
export const VERIFY_ACCOUNT_SUCSESS='VERIFY_ACCOUNT_SUCSESS';
export const VERIFY_ACCOUNT_FAIL='VERIFY_ACCOUNT_FAIL';

//login
export const LOGIN_ACCOUNT='LOGIN_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS='LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAIL='LOGIN_ACCOUNT_FAIL';